"""create paper and block tables

Revision ID: 57ece2f26c28
Revises: 
Create Date: 2026-10-04 16:20:49.564095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57ece2f26c28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('parsing', 'ready', 'failed', name='paperstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_user_id'), ['user_id'], unique=False)

    op.create_table('block',
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('heading', 'paragraph', 'caption', 'figure', name='blocktype'), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x0', sa.Float(), nullable=False),
    sa.Column('y0', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('section_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'id')
    )
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_seq'), ['seq'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_seq'))

    op.drop_table('block')
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_user_id'))

    op.drop_table('paper')
    # ### end Alembic commands ###
