"""add paper source metadata

Revision ID: 61a85f940069
Revises: b23930d5d5b7
Create Date: 2026-10-05 20:40:25.824222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61a85f940069'
down_revision: Union[str, Sequence[str], None] = 'b23930d5d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arxiv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('metadata_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('metadata_source')
        batch_op.drop_column('doi')
        batch_op.drop_column('arxiv_id')
        batch_op.drop_column('year')
        batch_op.drop_column('authors')

    # ### end Alembic commands ###
