"""add sentences, abstract, language, hidden text

Revision ID: b23930d5d5b7
Revises: 57ece2f26c28
Create Date: 2026-10-05 20:28:38.186495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b23930d5d5b7'
down_revision: Union[str, Sequence[str], None] = '57ece2f26c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], name=op.f('fk_sentence_paper_id_paper'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'block_id', 'idx', name=op.f('pk_sentence'))
    )
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), server_default='en', nullable=False))
        batch_op.add_column(sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('hidden_text_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('parser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_paper_user_id_sha256'), ['user_id', 'sha256'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_paper_user_id_sha256'), type_='unique')
        batch_op.drop_column('parser_version')
        batch_op.drop_column('hidden_text_count')
        batch_op.drop_column('abstract')
        batch_op.drop_column('language')
        batch_op.drop_column('sha256')

    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_column('hidden')
        batch_op.drop_column('level')

    op.drop_table('sentence')
    # ### end Alembic commands ###
